// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYGbFjIsV65ISA8P3KEB3r45IN1A3ucXc',
    appId: '1:359987363803:web:fd875de3b46ad8f44ef1fe',
    messagingSenderId: '359987363803',
    projectId: 'bokit-eafed',
    authDomain: 'bokit-eafed.firebaseapp.com',
    storageBucket: 'bokit-eafed.appspot.com',
    measurementId: 'G-98JXCJ11YX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXv89C8TJFHyzksnrKcHTxZbTsVYGDjNg',
    appId: '1:359987363803:android:5b5ff1e3cfcce29c4ef1fe',
    messagingSenderId: '359987363803',
    projectId: 'bokit-eafed',
    storageBucket: 'bokit-eafed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4koCxXlRywf_2hPqiEpsy3Bz20xbHO4o',
    appId: '1:359987363803:ios:8fcddd6b94216cda4ef1fe',
    messagingSenderId: '359987363803',
    projectId: 'bokit-eafed',
    storageBucket: 'bokit-eafed.appspot.com',
    iosBundleId: 'com.unlimited.hagzz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4koCxXlRywf_2hPqiEpsy3Bz20xbHO4o',
    appId: '1:359987363803:ios:02f5038d26ef9a634ef1fe',
    messagingSenderId: '359987363803',
    projectId: 'bokit-eafed',
    storageBucket: 'bokit-eafed.appspot.com',
    iosBundleId: 'com.bookit.bookit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYGbFjIsV65ISA8P3KEB3r45IN1A3ucXc',
    appId: '1:359987363803:web:b2c2ac112b5496114ef1fe',
    messagingSenderId: '359987363803',
    projectId: 'bokit-eafed',
    authDomain: 'bokit-eafed.firebaseapp.com',
    storageBucket: 'bokit-eafed.appspot.com',
    measurementId: 'G-B2RKRPV7MP',
  );

}